export const SIGNUP = 'SIGNUP'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'

export const SIGNIN = 'SIGNIN'
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE'

export const LOGOUT = 'LOGOUT'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'

export const CALLOBJ = 'CALLOBJ'
export const CALLOBJ_SUCCESS = 'CALLOBJ_SUCCESS'
export const CALLOBJ_FAILURE = 'CALLOBJ_FAILURE'

export const WORKSPACE = 'WORKSPACE'
export const WORKSPACE_SUCCESS = 'WORKSPACE_SUCCESS'
export const WORKSPACE_FAILURE = 'WORKSPACE_FAILURE'

export const COLLABORATION = "COLLABORATION"
export const COLLABORATION_SUCCESS = "COLLABORATION_SUCCESS"
export const COLLABORATION_FAILURE = "COLLABORATION_FAILURE"

export const COLLABORATIONWID = "COLLABORATIONWID"